
sudo: false

jobs:
  include:
    - stage: build-client
      language: node_js
      node_js:
        - 10.15.3

      install:
        - npm install -g ionic@5.4.6 cordova@8.1.2

      before_script:
        - wget -q http://dl.google.com/android/android-sdk_r24.4-linux.tgz
        - tar -xf android-sdk_r24.4-linux.tgz
        - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter platform-tools
        - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter build-tools-23.0.2
        - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter android-23
        - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-android-support
        - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-android-m2repository
        - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-google-m2repository
        - export ANDROID_HOME=$PWD/android-sdk-linux
        - export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/23.0.2
      script:
        - cd client
        - npm install
        - ionic cordova prepare android
        - ionic cordova build android

    - stage: build-backend-service
      language: java
      script:
        - cd server
        - mvn deploy -q
    - stage: build-backend-image
      services:
        - docker
      script:
        - cd server
        - docker build . -t rgse/brewlog-server:$TRAVIS_COMMIT
    -stage: publish
      if: tag IS present
      services:
        - docker
      script:
        - docker tag rgse/brewlog-server:$TRAVIS_COMMIT rgse/brewlog-server:$TRAVIS_TAG
        - docker login -u $DOCKER_USER -p $DOCKER_TOKEN
        - docker push rgse/brewlog-server:$TRAVIS_TAG
