package de.rgse.brewlog.process.util;

public enum FirebaseVariables {
	FIREBASE_APIKEY, FIREBASE_AUTH_DOMAIN, FIREBASE_DATABASE_URL, FIRERBASE_PROJECT_ID, FIREBASE_STORAGE_BUCKET, FIREBASE_MESSAGING_SENDER_ID,FIREBASE_APP_ID
}
